on:
  push:
    branches: [master]

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS_ACCESS_KEY_ID
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      
    - name: Configure AWS_SECRET_ACCESS_KEY
      run: |
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     
    - name: Switch Role 1
      run: |
        aws configure set role_arn arn:aws:iam::248239598373:role/DeveloperRole --profile DeveloperRole
    - name: Switch Role 2
      run: |
        aws configure set source_profile default --profile DeveloperRole
    - name: Switch Role 3
      run: |  
        aws configure set region ap-northeast-2 --profile DeveloperRole
    
    - name: Switch Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-2
        role-to-assume: arn:aws:iam::248239598373:role/DeveloperRole

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: my-app-container
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: my-app-ecs-service
        cluster: my-app-cluster
        wait-for-service-stability: true
